export const GET_ROUTE = 'GET_ROUTE';
export const GET_ROUTE_SUCCESS = 'GET_ROUTE_SUCCESS';
export const GET_ROUTE_FAILURE = 'GET_ROUTE_FAILURE';

export const GET_ROUTES = 'GET_ROUTES';
export const GET_ROUTES_SUCCESS = 'GET_ROUTES_SUCCESS';
export const GET_ROUTES_FAILURE = 'GET_ROUTES_FAILURE';

export const GET_VEHICLES = 'GET_VEHICLES';
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS';

export const ACTIVATE_DIRECTION = 'ACTIVATE_DIRECTION';
export const CLOSE_ROUTE = 'CLOSE_ROUTE';
export const SEARCH_TERM = 'SEARCH_TERM';
export const STOP_HOVERED = 'STOP_HOVERED';
export const STOP_SELECTED = 'STOP_SELECTED';